function [fitresult, gof] = createFit(TimeFit, IntensityFit)
%CREATEFIT(TIMEFIT,INTENSITYFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: TimeFit
%      Y Output: IntensityFit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Sep-2023 12:05:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( TimeFit, IntensityFit );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0.085634666002705 -3.22399306848561 25.3077732446921 -0.00466949727123623];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
%legend( h, 'IntensityFit vs. TimeFit', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Time', 'Interpreter', 'none' );
ylabel( 'Intensity', 'Interpreter', 'none' );
grid on


