%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: U:\Projekte an Analysis1\Christian\Misc\Hannah\vCMC_Cdh5Cre_Tam-_ transients_04.txt
%
% Auto-generated by MATLAB on 04-Sep-2023 10:57:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Time", "Intensity"];
opts.SelectedVariableNames = ["Time", "Intensity"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
file = uigetfile('*.txt');

% Import the data
tbl = readtable(file, opts);
tbl = smoothdata(tbl,"movmedian",50,"DataVariables","Intensity");
%% Convert to output type
Time = tbl.Time;
Intensity = tbl.Intensity;

%% Clear temporary variables
clear opts tbl file

%% Peaks
 
[pks,timePeak] = findpeaks(Intensity, Time ,'MinPeakProminence',10,'MinPeakDistance', 2); %Prominence: https://de.mathworks.com/help/signal/ug/prominence.html
peakInterval = diff(timePeak);
plot(Time,Intensity, timePeak,pks,'o')
xlabel('Time (s)')
ylabel('Intensity')
figure;
histogram(peakInterval)
grid on
xlabel('Time Intervals')
ylabel('Frequency of Occurrence')
AverageDistance_Peaks = mean(diff(timePeak))
for i = 1: numel(timePeak)
     [~, ix1] = min(abs(Time - (timePeak(i)+0.1)));
     [~, ix2] = min(abs(Time - (timePeak(i)+1.8)));
     [~, ix3] = min(abs(Time - (timePeak(i)-1)));
     [~, ix4] = min(abs(Time - (timePeak(i)+1)));
    TimeFit = Time(ix1:ix2);
    IntensityFit = Intensity(ix1:ix2);
    [fitresult, gof] = createFit(TimeFit, IntensityFit);
    tauFast = log(1/2) / fitresult.b;
    tauSlow = log(1/2) / fitresult.d;
    gof.tauSlow = tauSlow;
    gof.tauFast = tauFast;
    fitData(i) = struct('fit', fitresult, 'fitInfo', gof, 'Intensity', IntensityFit, 'Time', TimeFit);

    TimeTimeToCalc = Time(ix3:ix4);
    IntensityTimeToCalc = Intensity(ix3:ix4);
   
    ipt = findchangepts(IntensityTimeToCalc,'Statistic',"std",'MaxNumChanges', 1);
    plot(TimeTimeToCalc, IntensityTimeToCalc);
    xline(TimeTimeToCalc(ipt), 'Color', 'red');
    yline(IntensityTimeToCalc(ipt), 'Color', 'red');
    timePeakStart(i) = ipt;
end

for i = 1: numel(timePeak)
    fastTaus(i) = fitData(i).fitInfo.tauFast;
    slowTaus(i) = fitData(i).fitInfo.tauSlow;
end

median(slowTaus)
std(slowTaus)
figure;bar(slowTaus)
median(fastTaus)
std(fastTaus)
figure;bar(fastTaus)