function HEK293ThTRPM8IRES2cpmCherry2000ng1060B1P58RT50uMAzoAktDeakt113 = importfileRamps(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  HEK293THTRPM8IRES2CPMCHERRY2000NG1060B1P58RT50UMAZOAKTDEAKT113 =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  HEK293THTRPM8IRES2CPMCHERRY2000NG1060B1P58RT50UMAZOAKTDEAKT113 =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  HEK293ThTRPM8IRES2cpmCherry2000ng1060B1P58RT50uMAzoAktDeakt113 = importfile1("U:\Projekte an Analysis1\Clara\TRPM8\Messungen Patch3\Exportierte Daten AktDeakt AktInakt\TRPM8 1060\RT AktDeakt 1060\HEK293T_hTRPM8_IRES2_cpmCherry(2000ng1060)_B1P58_RT_50uMAzo_AktDeakt_1-1(3).asc", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Mar-2023 11:30:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Index", "Max", "Times", "ImonA_Neg", "ImonA"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Max", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Index", "Times", "ImonA_Neg", "ImonA"], "ThousandsSeparator", ",");

% Import the data
HEK293ThTRPM8IRES2cpmCherry2000ng1060B1P58RT50uMAzoAktDeakt113 = readtable(filename, opts);

end